name: count_env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.9  
  - numpy
  - matplotlib
  - tqdm
  - tensorboard
  - scipy
  - opencv  
  - pip  
  - pip:
      - torch==1.10.0+cu111
      - torchvision==0.11.0+cu111
      - torchaudio==0.10.0
      - timm==0.4.12
      - imgaug
      - hub
      - gdown
      - wandb
